import { useMemo, useState } from "react";
import { Sparkles } from "lucide-react";
import { Badge, Button, Callout, Drawer, EmptyState, Select, SkeletonText, Stepper, TextField, Toggle, cn, panel } from "../../../ui";
import { useAutoCreate, useAutoProposal } from "../api";
import { type Selection, buildSelection, defaultFormName, defaultSelection, depthsFor, detectedDepth, missingUnits, rulePaths } from "../autoGenerate";
import { fieldTitle } from "../builder";
import { type Site, errorMessage } from "../logic";

const STEPS = [
  { id: "where", label: "Site and category" },
  { id: "groups", label: "Unit groups" },
  { id: "review", label: "Proposal" },
];
const SHOWN_RULES = 8;

export type AutoGenerateDrawerProps = {
  sites: Site[];
  initial: { siteId: number | null; categoryId: number | null };
  onClose: () => void;
  /** The new form's id; the builder opens on it for review. */
  onCreated: (id: number | null, name: string) => void;
};

/**
 * Auto-generate (AI): the site's factor names, grouped by unit, become fields,
 * dependent choices and factor rules. Pick the unit groups and their depth,
 * check the proposal, then review the form in the builder.
 */
export function AutoGenerateDrawer({ sites, initial, onClose, onCreated }: AutoGenerateDrawerProps) {
  const [step, setStep] = useState(initial.siteId && initial.categoryId ? 1 : 0);
  const [siteId, setSiteId] = useState(initial.siteId);
  const [categoryId, setCategoryId] = useState(initial.categoryId);
  const proposal = useAutoProposal(step > 0 ? siteId : null, step > 0 ? categoryId : null);
  const [picked, setPicked] = useState<{ key: string; sel: Selection } | null>(null);
  const [createUnits, setCreateUnits] = useState(true);
  const [name, setName] = useState<string | null>(null);
  const create = useAutoCreate();

  const key = `${siteId}:${categoryId}`;
  const p = proposal.data;
  // Selection belongs to the pair it was made for; a new pair starts from the detected depths.
  const sel = useMemo(() => (picked?.key === key ? picked.sel : p ? defaultSelection(p) : new Map<number, number>()), [picked, key, p]);
  const generated = useMemo(() => (p ? buildSelection(p, sel) : null), [p, sel]);
  const formName = name ?? (p ? defaultFormName(p, sel) : "");
  const missing = p ? missingUnits(p) : [];

  const site = sites.find((s) => s.site_id === siteId);
  const setSel = (next: Selection) => setPicked({ key, sel: next });
  const toggleGroup = (i: number, on: boolean) => {
    if (on && p) setSel(new Map(sel).set(i, detectedDepth(p.configs[i])));
    else if (sel.size > 1) setSel(new Map([...sel].filter(([g]) => g !== i)));
  };

  const close = () => !create.isPending && onClose();
  const submit = () => {
    if (!p || !generated || !formName.trim()) return;
    create.mutate(
      {
        site_id: p.site_id,
        category_id: p.category_id,
        config_name: formName.trim(),
        columns: generated.columns,
        column_options: generated.options,
        column_dependencies: generated.deps,
        dependent_options: generated.depOpts,
        emission_category_mapping: generated.mappings,
        create_units: createUnits,
        proposed_units: createUnits ? missing : [],
      },
      { onSuccess: (res) => onCreated(res?.columnConfig?.pk_id ?? null, formName.trim()) },
    );
  };

  const ready = step === 0 ? !!siteId && !!categoryId : step === 1 ? !!p && sel.size > 0 : !!formName.trim() && !!generated;
  const footer = (
    <div className="flex justify-between gap-2">
      <Button onClick={() => (step === 0 ? close() : setStep(step - 1))} disabled={create.isPending}>
        {step === 0 ? "Cancel" : "Back"}
      </Button>
      {step < 2 ? (
        <Button variant="primary" onClick={() => setStep(step + 1)} disabled={!ready}>
          Next
        </Button>
      ) : (
        <Button variant="primary" onClick={submit} disabled={!ready} loading={create.isPending}>
          Create and review
        </Button>
      )}
    </div>
  );

  return (
    <Drawer open onClose={close} size="lg" title="Auto-generate a form" subtitle={site ? [site.name, site.categories?.find((c) => c.category_id === categoryId)?.category_name].filter(Boolean).join(" · ") : undefined} footer={footer}>
      <div className="space-y-4">
        <Stepper steps={STEPS} current={step} completed={STEPS.slice(0, step).map((s) => s.id)} label="Auto-generate progress" />

        {step === 0 && (
          <div className="grid gap-3 sm:grid-cols-2">
            <Select<number>
              label="Site"
              value={siteId}
              onChange={(v) => {
                setSiteId(v);
                setCategoryId(null);
              }}
              options={[...sites].sort((a, b) => a.name.localeCompare(b.name)).map((s) => ({ value: s.site_id, label: s.company ? `${s.name} (${s.company.name})` : s.name }))}
              placeholder="Choose a site"
            />
            <Select<number>
              label="Category"
              value={categoryId}
              onChange={setCategoryId}
              options={(site?.categories ?? []).map((c) => ({ value: c.category_id, label: c.category_name })).sort((a, b) => a.label.localeCompare(b.label))}
              placeholder="Choose a category"
              emptyText={site ? "This site has no categories" : "Choose a site first"}
            />
          </div>
        )}

        {step > 0 && proposal.isPending && (
          <div aria-busy="true" className="space-y-2">
            <p className="flex items-center gap-1.5 text-sm text-muted">
              <Sparkles aria-hidden className="size-4" /> Reading this site's emission factors…
            </p>
            <SkeletonText lines={5} />
          </div>
        )}
        {step > 0 && proposal.error && (
          <EmptyState variant="error" compact title="Couldn't build a proposal." description={errorMessage(proposal.error, "Try again.")} action={<Button onClick={() => void proposal.refetch()}>Try again</Button>} />
        )}
        {step > 0 && p && p.configs.length === 0 && (
          <EmptyState icon={Sparkles} compact title="No emission factors to build from." description="Add factors for this site and category first, or create the form by hand." />
        )}

        {step === 1 && p && p.configs.length > 0 && (
          <>
            {p.existing_config_ids.length > 0 && (
              <Callout tone="warn" title={`This site and category already has ${p.existing_config_ids.length === 1 ? "a form" : `${p.existing_config_ids.length} forms`}`}>
                Auto-generate adds another one.
              </Callout>
            )}
            <ul className="space-y-2" aria-label="Unit groups">
              {p.configs.map((g, i) => {
                const on = sel.has(i);
                const depths = depthsFor(g);
                return (
                  <li key={`${g.denominator_unit}-${i}`} className={cn(panel, "flex flex-wrap items-end justify-between gap-3 p-3")}>
                    <Toggle
                      label={`Per ${g.denominator_unit}`}
                      checked={on}
                      onChange={(v) => toggleGroup(i, v)}
                      disabled={on && sel.size === 1}
                      inlineLabel={`${(g.ef_name_pairs?.length || g.ef_names.length).toLocaleString("en-GB")} factors`}
                    />
                    {on && depths.length > 1 && (
                      <Select<number>
                        label="Levels of choices"
                        className="w-56"
                        value={sel.get(i) ?? null}
                        onChange={(v) => v && setSel(new Map(sel).set(i, v))}
                        options={depths.map((d) => ({ value: d, label: (g.column_names_by_dim?.[d]?.columns ?? []).filter((c) => c.column_type === "select").map((c) => fieldTitle(c.column_name)).join(" › ") || `${d} ${d === 1 ? "level" : "levels"}` }))}
                      />
                    )}
                  </li>
                );
              })}
            </ul>
            {missing.length > 0 && (
              <Toggle
                label="Also create missing units"
                checked={createUnits}
                onChange={setCreateUnits}
                inlineLabel={missing.map((u) => u.unit_name).join(", ")}
                help="Contributors can only pick units that exist for this site and category."
              />
            )}
          </>
        )}

        {step === 2 && p && generated && (
          <div className="space-y-4">
            <TextField label="Form name" value={formName} onChange={setName} required error={formName.trim() ? undefined : "Enter a name."} />
            <section aria-label="Fields" className="space-y-2">
              <h3 className="text-sm font-semibold text-ink">Fields</h3>
              <ul className="space-y-1.5">
                {generated.columns.map((c) => {
                  const choices = generated.options[c.column_name]?.length ?? 0;
                  const parent = generated.deps[c.column_name];
                  return (
                    <li key={c.column_name} className="flex flex-wrap items-center gap-2 text-sm">
                      <span className="font-medium text-ink">{fieldTitle(c.column_name)}</span>
                      <Badge tone="neutral">{c.column_type === "select" ? "Select" : "Number"}</Badge>
                      {c.is_new && <Badge tone="info">New column</Badge>}
                      {c.column_type === "select" && (
                        <span className="text-muted">
                          {choices} {choices === 1 ? "choice" : "choices"}
                          {parent ? `, by ${fieldTitle(parent).toLowerCase()}` : ""}
                        </span>
                      )}
                    </li>
                  );
                })}
              </ul>
            </section>
            <section aria-label="Factor rules" className="space-y-2">
              <h3 className="text-sm font-semibold text-ink">Factor rules ({Object.keys(generated.mappings).length.toLocaleString("en-GB")})</h3>
              <ul className="space-y-1 text-sm text-ink">
                {rulePaths(generated)
                  .slice(0, SHOWN_RULES)
                  .map((r) => (
                    <li key={r}>{r}</li>
                  ))}
              </ul>
              {Object.keys(generated.mappings).length > SHOWN_RULES && <p className="text-xs text-muted">and {Object.keys(generated.mappings).length - SHOWN_RULES} more. All of them are in the builder's Factor match tab.</p>}
            </section>
            <p className="text-sm text-muted">The form is created now and opens in the builder, where you can rename fields, edit choices and rules, and test it before contributors use it.</p>
            {create.error && (
              <Callout tone="warn" title="Not created">
                {errorMessage(create.error, "Nothing was created. Try again.")}
              </Callout>
            )}
          </div>
        )}
      </div>
    </Drawer>
  );
}
