import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  type ColumnConfigProposal,
  type ConfirmAutoGenerateData,
  confirmAutoGenerateColumnConfig,
  createColumnConfig,
  deleteColumnConfig,
  getColumnConfigById,
  getColumnConfigs,
  previewAutoGenerateColumnConfig,
  updateColumnConfig,
} from "../../services/columnConfigService";
import { getEmissionCategoryNames, getUserEmissionFactorsBySiteAndCategory } from "../../services/emissionFactorService";
import { getUserUnitsBySiteAndCategory, type UnitData } from "../../services/unitService";
import type { EmissionFactor } from "../../lib/emissions/types";
import { createColumn, deleteColumn, getColumns, updateColumn } from "../../services/columnService";
import { getSites } from "../../services/siteService";
import type { ColumnDraft, FormConfig, LibraryColumn, Site } from "./logic";
import { toPayload } from "./logic";
import type { SourceConfig, UpdatePayload } from "./builder";

export const keys = {
  all: ["capture-setup"] as const,
  configs: () => [...keys.all, "configs"] as const,
  columns: () => [...keys.all, "columns"] as const,
  sites: () => [...keys.all, "sites"] as const,
};

/** Lists arrive bare or wrapped (`{ sites: [...] }`); always hand back an array. */
function asList<T>(data: unknown, key: string): T[] {
  if (Array.isArray(data)) return data as T[];
  const inner = (data as Record<string, unknown> | null)?.[key];
  return Array.isArray(inner) ? (inner as T[]) : [];
}

export const useForms = () =>
  useQuery<FormConfig[]>({ queryKey: keys.configs(), queryFn: async () => asList<FormConfig>(await getColumnConfigs(), "columnConfigs") });
export const useLibrary = () =>
  useQuery<LibraryColumn[]>({ queryKey: keys.columns(), queryFn: async () => asList<LibraryColumn>(await getColumns(), "columns") });
export const useSites = () =>
  useQuery<Site[]>({ queryKey: keys.sites(), queryFn: async () => asList<Site>(await getSites(), "sites"), staleTime: 5 * 60_000 });

export function useSaveColumn() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, draft }: { id: number | null; draft: ColumnDraft }) =>
      id === null ? createColumn(toPayload(draft)) : updateColumn(id, toPayload(draft)),
    // Forms embed their columns, so both lists change.
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

export function useDeleteColumn() {
  const qc = useQueryClient();
  return useMutation({
    // data-loss-reviewed: deletes one unused library column after a confirm dialog naming it; columns in use are blocked with a list of their forms
    mutationFn: (id: number) => deleteColumn(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.columns() }),
  });
}

export function useCreateForm() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (d: { name: string; siteId: number; categoryId: number }) =>
      createColumnConfig({ config_name: d.name.trim(), site_id: d.siteId, category_id: d.categoryId }) as Promise<{
        columnConfig?: { pk_id?: number };
        pk_id?: number;
      }>,
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

export function useDeleteForm() {
  const qc = useQueryClient();
  return useMutation({
    // data-loss-reviewed: deletes one data-entry form after a destructive confirm naming the form, site and category; saved entries are kept
    mutationFn: (id: number) => deleteColumnConfig(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

/** The new form's id, whichever shape the create response has. */
export function createdId(res: { columnConfig?: { pk_id?: number }; pk_id?: number } | undefined): number | null {
  return res?.columnConfig?.pk_id ?? res?.pk_id ?? null;
}

export const formKey = (id: number) => [...keys.configs(), id] as const;

/** One form with its columns, site and category. */
export const useForm = (id: number | null) =>
  useQuery<SourceConfig>({
    queryKey: formKey(id ?? 0),
    queryFn: async () => {
      const data = (await getColumnConfigById(id as number)) as SourceConfig | { columnConfig: SourceConfig };
      return "columnConfig" in data ? data.columnConfig : data;
    },
    enabled: !!id,
  });

/** Emission categories with a factor for this site and category: the Factor match targets. */
export const useFactorNames = (categoryId: number | null | undefined, siteId: number | null | undefined) =>
  useQuery<string[]>({
    queryKey: [...keys.all, "factor-names", categoryId, siteId],
    queryFn: async () => asList<string>(await getEmissionCategoryNames(categoryId as number, siteId ?? undefined), "names"),
    enabled: !!categoryId,
    staleTime: 5 * 60_000,
    retry: 1,
  });

/** Every factor year for this site and category, and its units: what the Test tab calculates with. */
export const useTestSetup = (siteId: number | null | undefined, categoryId: number | null | undefined) =>
  useQuery<{ factors: EmissionFactor[]; units: string[] }>({
    queryKey: [...keys.all, "test-setup", siteId, categoryId],
    queryFn: async () => {
      const [factors, units] = await Promise.all([
        getUserEmissionFactorsBySiteAndCategory(siteId as number, categoryId as number) as Promise<EmissionFactor[]>,
        getUserUnitsBySiteAndCategory(siteId as number, categoryId as number) as Promise<UnitData[]>,
      ]);
      return { factors: Array.isArray(factors) ? factors : [], units: Array.isArray(units) ? units.map((u) => u.unit_name) : [] };
    },
    enabled: !!siteId && !!categoryId,
    staleTime: 5 * 60_000,
  });

export function useSaveForm(id: number) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: UpdatePayload) =>
      updateColumnConfig(id, payload) as Promise<{ columnConfig?: SourceConfig; migrationWarning?: boolean; message?: string }>,
    onSuccess: (res) => {
      if (res?.columnConfig) qc.setQueryData(formKey(id), res.columnConfig);
      // Renames can create library columns; the list shows every form.
      void qc.invalidateQueries({ queryKey: keys.columns() });
      void qc.invalidateQueries({ queryKey: keys.configs(), exact: true });
    },
  });
}

/** The AI proposal for a site and category: factor names grouped by unit. Asked for once per pair. */
export const useAutoProposal = (siteId: number | null, categoryId: number | null) =>
  useQuery<ColumnConfigProposal>({
    queryKey: [...keys.all, "auto-proposal", siteId, categoryId],
    queryFn: () => previewAutoGenerateColumnConfig(siteId as number, categoryId as number),
    enabled: !!siteId && !!categoryId,
    staleTime: Infinity,
    retry: false,
  });

export function useAutoCreate() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: ConfirmAutoGenerateData) => confirmAutoGenerateColumnConfig(data),
    // New library columns and units may come with the form.
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}
